# Generated by Django 5.0.6 on 2024-05-27 11:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidences",
            options={"verbose_name_plural": "Incidences"},
        ),
        migrations.AlterField(
            model_name="incidences",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
