# Generated by Django 5.0.6 on 2024-05-27 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporter", "0002_alter_incidences_options_alter_incidences_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sub_Counties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("constituen", models.CharField(max_length=50)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
