# Generated by Django 5.0.6 on 2024-05-13 14:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NairobiHealthFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "addr_city",
                    models.CharField(
                        blank=True, db_column="addr:city", max_length=254, null=True
                    ),
                ),
                (
                    "addr_stree",
                    models.CharField(
                        blank=True, db_column="addr:street", max_length=254, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, db_column="contact:phone", max_length=254, null=True
                    ),
                ),
            ],
            options={
                "db_table": "nairobi_health_facilities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NairobiSubCounties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("constituen", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "nairobi_sub_counties",
                "managed": False,
            },
        ),
    ]
